### ISSUE TITLE
[Anon] Bug report: Space Marine Scouts.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#55] opened 2017-04-20 21:28 UTC
**File:** Space Marine Scouts.catz

**BattleScribe version:** 2.00.16

**Platform:** Windows

**Dropbox:** No

**Description:** This version of the file will not load an old team or let you start a new team on the Windows client. It loads an empty list of classes etc...

It actually crashes the app on iOS when trying to load a team or start a new one.

The other newest data files for the Kill Teams all seem to work.

**Comment by GenWilhelm** [comment] 2017-04-20 22:52
Duplicate of #54.

**Closed as completed by GenWilhelm** 2017-04-20 22:52 UTC
Labels: duplicate
