### ISSUE TITLE
[Anon] Bug report: Ork Boyz.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#28] opened 2017-04-12 10:53 UTC
**File:** Ork Boyz.catz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** In this file Orks can choose between 2 types of scope: red dot and telescopic. In the rebook they only take the red dot. Also the point cost is wrong, should be 15pts, here it's 20.

Cya

**Comment by GenWilhelm** [comment] 2017-04-12 11:09
Duplicate of #24.

**Closed as completed by GenWilhelm** 2017-04-12 11:09 UTC
Labels: duplicate
